export const ADMIN_PROFILE_CODES = [
  'SUPER_ADMIN',
  'ROOM_STATUS_VIEWER',
  'OPERATIONS_MANAGER',
  'HOUSEKEEPING_MANAGER',
  'HOUSEKEEPING_STAFF',
  'PAYMENT_STAFF',
  'MAINTENANCE_MANAGER',
  'MAINTENANCE_STAFF',
  'STAFF_MANAGER',
] as const;
export type AdminProfileCode = (typeof ADMIN_PROFILE_CODES)[number];

export const ADMIN_PROFILE_LABELS_VI: Readonly<Record<AdminProfileCode, string>> = {
  SUPER_ADMIN: 'Tổng quản trị',
  ROOM_STATUS_VIEWER: 'Nhân viên theo dõi phòng',
  OPERATIONS_MANAGER: 'Quản lý vận hành',
  HOUSEKEEPING_MANAGER: 'Quản lý buồng phòng',
  HOUSEKEEPING_STAFF: 'Nhân viên buồng phòng',
  PAYMENT_STAFF: 'Nhân viên thanh toán',
  MAINTENANCE_MANAGER: 'Quản lý bảo trì',
  MAINTENANCE_STAFF: 'Nhân viên bảo trì',
  STAFF_MANAGER: 'Quản lý nhân sự',
};

export const PERMISSIONS = [
  'dashboard.read',
  'bookings.read',
  'bookings.manage',
  'bookings.checkin',
  'bookings.checkout',
  'bookings.cancel',
  'customers.read',
  'customers.manage',
  'customers.sessions.revoke',
  'rooms.read',
  'rooms.manage',
  'room_operations.read',
  'room_operations.manage',
  'housekeeping.task.read',
  'housekeeping.task.update',
  'housekeeping.task.manage',
  'maintenance.read',
  'maintenance.manage',
  'payments.read',
  'payments.reconcile',
  'payments.refund',
  'reviews.read',
  'reviews.manage',
  'catalog.read',
  'catalog.manage',
  'amenities.manage',
  'pricing.read',
  'pricing.manage',
  'coupons.manage',
  'providers.read',
  'providers.manage',
  'admin_accounts.read',
  'admin_accounts.manage',
  'departments.read',
  'departments.manage',
  'audit.read',
  'property.read',
  'property.manage',
  'catalog.property.read',
  'catalog.property.manage',
  'catalog.price_tier.read',
  'catalog.price_tier.manage',
  'catalog.room_type.read',
  'catalog.room_type.manage',
  'catalog.amenity.read',
  'catalog.amenity.manage',
  'catalog.room.read',
  'catalog.room.status.read',
  'catalog.room.manage',
  'catalog.maintenance.read',
  'catalog.maintenance.manage',
  'coupon.read',
  'coupon.manage',
  'pricing.rate_plan.read',
  'pricing.rate_plan.manage',
  'pricing.policy.read',
  'pricing.policy.draft.create',
  'pricing.policy.draft.update',
  'pricing.policy.preview',
  'pricing.policy.publish',
  'pricing.policy.retire',
  'booking.lifecycle.read',
  'booking.lifecycle.manage',
  'booking.review.read',
  'booking.review.manage',
  'payment.reconciliation.read',
  'payment.reconciliation.manage',
  'admin.account.read',
  'admin.account.manage',
  'admin.department.read',
  'admin.department.manage',
  'admin.audit.read',
] as const;

export type Permission = (typeof PERMISSIONS)[number];
export type HumanRole = 'ADMIN' | 'SUPER_ADMIN' | 'ROOM_STATUS_VIEWER' | 'CUSTOMER';

export const PROFILE_PERMISSIONS: Readonly<Record<AdminProfileCode, readonly Permission[]>> = {
  SUPER_ADMIN: PERMISSIONS,
  ROOM_STATUS_VIEWER: [
    'catalog.property.read',
    'catalog.room.read',
    'catalog.room.status.read',
    'catalog.maintenance.read',
    'rooms.read',
    'room_operations.read',
    'maintenance.read',
  ],
  OPERATIONS_MANAGER: [
    'dashboard.read',
    'bookings.read',
    'bookings.manage',
    'bookings.checkin',
    'bookings.checkout',
    'bookings.cancel',
    'customers.read',
    'rooms.read',
    'room_operations.read',
    'room_operations.manage',
    'housekeeping.task.read',
    'housekeeping.task.manage',
    'maintenance.read',
    'maintenance.manage',
    'catalog.read',
    'catalog.property.read',
    'catalog.room_type.read',
    'catalog.room.read',
    'catalog.room.status.read',
    'catalog.room.manage',
    'catalog.maintenance.read',
    'catalog.maintenance.manage',
    'booking.lifecycle.read',
    'booking.lifecycle.manage',
    'booking.review.read',
    'pricing.read',
    'audit.read',
    'admin.audit.read',
  ],
  HOUSEKEEPING_MANAGER: [
    'dashboard.read',
    'rooms.read',
    'room_operations.read',
    'room_operations.manage',
    'housekeeping.task.read',
    'housekeeping.task.manage',
    'maintenance.read',
    'catalog.property.read',
    'catalog.room_type.read',
    'catalog.room.read',
    'catalog.room.status.read',
    'catalog.room.manage',
    'catalog.maintenance.read',
    'booking.lifecycle.read',
    'audit.read',
  ],
  HOUSEKEEPING_STAFF: [
    'rooms.read',
    'room_operations.read',
    'housekeeping.task.read',
    'housekeeping.task.update',
    'catalog.property.read',
    'catalog.room.read',
    'catalog.room.status.read',
  ],
  PAYMENT_STAFF: [
    'dashboard.read',
    'bookings.read',
    'payments.read',
    'payments.reconcile',
    'payment.reconciliation.read',
    'payment.reconciliation.manage',
    'booking.review.read',
    'booking.review.manage',
    'audit.read',
  ],
  MAINTENANCE_MANAGER: [
    'dashboard.read',
    'rooms.read',
    'room_operations.read',
    'maintenance.read',
    'maintenance.manage',
    'catalog.property.read',
    'catalog.room.read',
    'catalog.room.status.read',
    'catalog.maintenance.read',
    'catalog.maintenance.manage',
    'audit.read',
  ],
  MAINTENANCE_STAFF: [
    'rooms.read',
    'room_operations.read',
    'maintenance.read',
    'catalog.property.read',
    'catalog.room.read',
    'catalog.room.status.read',
    'catalog.maintenance.read',
  ],
  STAFF_MANAGER: [
    'dashboard.read',
    'admin.account.read',
    'admin.account.manage',
    'admin.department.read',
    'catalog.property.read',
  ],
};

export const ROLE_PERMISSIONS: Readonly<Record<HumanRole, readonly Permission[]>> = {
  // Legacy ADMIN rows remain a top-level role for compatibility but do not
  // acquire an ADMIN V2 profile without an active membership.
  ADMIN: [],
  SUPER_ADMIN: PERMISSIONS,
  ROOM_STATUS_VIEWER: PROFILE_PERMISSIONS.ROOM_STATUS_VIEWER,
  CUSTOMER: [],
};

export function hasPermissions(role: HumanRole, required: readonly Permission[]): boolean {
  const granted = ROLE_PERMISSIONS[role];
  return required.every((permission) => granted.includes(permission));
}

export function getProfilePermissions(profileCode: AdminProfileCode): readonly Permission[] {
  return PROFILE_PERMISSIONS[profileCode];
}
